---
abstract: 'test directory attributes'
author:
  - 'Martin `Kingpin` Thurn <mthurn@cpan.org>'
build_requires:
  Pod::Coverage: 0
  Test::Builder::Tester: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Dir
no_index:
  directory:
    - inc
    - t
requires:
  Test::Builder: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.006
